---
- name: to copy tomcat user xml file into node side
  template:
      src: templates/tomuser.j2
      dest: /opt/tomcat/conf/tomcat-users.xml


    
- name: to copy tomcat context xml file into nodes
  template:
      src: templates/tomcontext.j2
      dest: /opt/tomcat/webapps/manager/META-INF/context.xml




- name: tomcat hostcontext xml file into nodes
  template:
      src: templates/tomhostcontext.j2
      dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml